# Generated by Django 4.2.2 on 2023-07-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_country_book_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
